[ 'ship-confirm@amazon.com',
  'nnicholas1984@gmail.com',
  'Your Orders',
  'Your Account',
  'Amazon.com',
  '112-3510611-1917001',
  'Your Orders',
  'Nine West Women\'s Austin Dress Pump,Dark Taupe Leather,10.5 M US',
  'Nine West Women\'s Austin Dress Pump,Blue,10.5 M US',
  '112-3510611-1917001',
  'Nine West Women\'s Austin Pump,Dark Brown Leather,10.5 M US',
  'Online Return Center',
  'Customer Service' ]

[ 'ship-confirm@amazon.com',
  'sierrajbrown@gmail.com',
  'Your Orders',
  'Your Account',
  'Amazon.com',
  '110-9800370-4877869',
  'Your Orders',
  'Garcinia Cambogia Extract - 1600 mg Servings (only 2 capsules/day)- Pure 100 % Natural GMO Free Effective Appetite Suppressant and Weight Loss Supplem',
  'Reserveage Organics Keratin Booster with Biotin and Resveratrol, 60 Vegetarian Capsules',
  'California Exotics Waterproof Jack Rabbit with Floating Beads, Purple',
  'Online Return Center',
  'Customer Service',
  'tax and seller information' ]